name: Examle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  MASTODON_URL: https://mastodon.social

jobs:
  example:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [native-tls, rustls-tls]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Run example
      run: cargo run --example mastodon_instance --features ${{ matrix.features }}
